---
dependency:
  name: galaxy
driver:
  name: docker
platforms:

  - name: ubuntu-1804-canonical
    image: geerlingguy/docker-ubuntu1804-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true
    privileged: true
    groups:
    - canonical_repo
    - ubuntu

  - name: ubuntu-1804-cuda
    image: geerlingguy/docker-ubuntu1804-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true
    privileged: true
    groups:
    - cuda_repo
    - ubuntu

  - name: ubuntu-2004-canonical-server
    image: geerlingguy/docker-ubuntu2004-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true
    privileged: true
    groups:
    - canonical_repo
    - ubuntu

  - name: ubuntu-2004-canonical-noserver
    image: geerlingguy/docker-ubuntu2004-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true
    privileged: true
    groups:
    - canonical_repo
    - canonical_repo_noserver
    - ubuntu

  - name: ubuntu-2004-cuda
    image: geerlingguy/docker-ubuntu2004-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true
    privileged: true
    groups:
    - cuda_repo
    - ubuntu

  - name: ubuntu-2204-canonical
    image: geerlingguy/docker-ubuntu2204-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true
    privileged: true
    groups:
    - canonical_repo
    - ubuntu

  - name: ubuntu-2204-cuda
    image: geerlingguy/docker-ubuntu2204-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true
    privileged: true
    groups:
    - cuda_repo
    - ubuntu

  - name: centos-7
    image: geerlingguy/docker-centos7-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true
    privileged: true

  - name: rockylinux-8
    image: geerlingguy/docker-rockylinux8-ansible
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
    pre_build_image: true
    privileged: true

provisioner:
  name: ansible
  ansible_args:
  - -vv
  inventory:
    group_vars:
      all:
        nvidia_driver_skip_reboot: true
      canonical_repo:
        nvidia_driver_ubuntu_install_from_cuda_repo: false
      canonical_repo_noserver:
        nvidia_driver_ubuntu_packages_suffix: ""
      cuda_repo:
        nvidia_driver_ubuntu_install_from_cuda_repo: true
verifier:
  name: ansible
